### ISSUE TITLE
App doesn't prevent adding the same item twice

### ISSUE THREAD

**Issue by axelsimon** [woefe/ShoppingList#12]
Hi and thanks for this app!
#### Bug
I've realised it's possible to add the same item twice. This is contradictory to the goal of a shopping list: put stuff on the list so you don't have to try and remember what you need to buy.
If I have to remember (or look) at the list when I add something to avoid adding it twice, then it defeats the purpose to some extent.

#### Suggested behaviour
When adding an item that already exists, either:
- filter the list while typing to show items that correspond, eventually showing that the item already exists
- ask the user "$item is already exists on the list, would you like to increment the number of $item you want to buy?"

**Comment by woefe** [comment]
Thanks for the report. I agree, it should not be possible to add duplicates to a list. I'm afraid, I will not implement your suggested behaviour for now, because:
* Asking to increment the number of items won't work, because the amount-text-field allows strings like "500g" or "1 package". I.e. there is no universal way to increment the amount
* Filtering and autocompletion might conflict (I will have to wait and see how it actually turns out)

But I will design the autocompletion mechanism so that it does not suggest items that are already on the list.

**Comment by woefe** [comment]
And I will also make sure that an item cannot be added twice. I will only show a Toast (popup) notifying the user that the item is already on the list

**Comment by woefe** [comment]
I decided to allow duplicates, but show a little warning, if the item is already on the list. The main reason for that is the underlying data structure, which are simple text files. I assume that these files can be changed externally and there is no way to enforce that there are no duplicate lines in these files.
