### ISSUE TITLE
Synchronising ShoppingList using Nextcloud (and maybe others) is too hard

### ISSUE THREAD

**Issue by axelsimon** [woefe/ShoppingList#13]
Hi,
I tried to get my ShoppingList to synchronise using Nextcloud but haven't been able too.

I created a directory in Nextcloud to store my Shopping List, entered the full path in ShoppingList's settings (in my case: /storage/sdcard1/Android/media/com.nextcloud.client/nextcloud/myuser\@myserv.er%2Fnextcloud_path/Shared/ShoppingList BTW, copy pasting a path is not a very fun experience in Android) and… nothing.

I can't tell if ShoppingList has picked the change up, if the path is valid (or not). The '@' is escaped because I copy/pasted from my terminal app, but I have no idea if that's necessary or not.
Also, there is bug #1 that makes me think it's not goinq to work anyway, because Nextcloud saves to my SD card.
Creating new test lists doesn't make them (or the original one) in the Nextcloud directory.

If one of ShoppingList's listed features is synchronising a shopping list, I believe some effort should be made to make that better documentend (bug #9) and easier to use.

Thanks!

**Comment by woefe** [comment]
Yeah I know there are some rough edges.

1) A proper directory chooser is coming in #9. It's the next thing I'll implement.
2) Unfortunately, I cannot test with an external SD card :(
3) Nextcloud for Android does not work like the desktop client. It cannot watch a folder for changes. For proper Nextcloud integration I will have to implement things manually, which I will do sooner or later, because I use it myself. I will open a new issue for that.

I think Syncthing could actually sync your files on Anrdoid like the Nextcloud client does on your Desktop.

**Comment by woefe** [comment]
Closed in favor of #9 and #17
